language: node_js

node_js:
  - "0.10.33"

before_install:
# install squid as proxy server
- sudo apt-get update
- sudo apt-get install -y squid3 net-tools ufw

install:
- npm install

before_script:
# test once before trying proxies
- npm test
# create firewall to block traffic except through https://127.0.0.1:3128 (squid)
- echo y | sudo ufw enable
- sudo ufw deny out https
- sudo ufw deny out http
- sudo iptables -I OUTPUT -p tcp --dport 443 -m owner --uid-owner `id -u proxy` -j ACCEPT
- sudo iptables -I OUTPUT -p tcp --dport 80  -m owner --uid-owner `id -u proxy` -j ACCEPT

script:
- export HTTP_PROXY=http://127.0.0.1:3128
- export HTTPS_PROXY=https://127.0.0.1:3128
- node --enable-ssl3 ./node_modules/.bin/_mocha ./test/*js
# ensure invalid proxy configuration fails
#- export HTTP_PROXY=http://invalid:3128
#- export HTTPS_PROXY=https://invalid:3128
#- INSTALL_RESULT=$(npm test > /dev/null)$? || true;
#- if [[ $INSTALL_RESULT == 0 ]]; then false; else echo "success... invalid proxy failed as expected"; fi;
